# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e12c111a7123c076779ab1b03d63b7c206ea80c0ab4e686d35a40069ab7fb2ec8c8d99c4bf0d1f04a107b06e237c6d208c811d8d402a0cb14b41987c1e6c3b

test:
  secret_key_base: 6a5f20bc919290ec98bcec8e8569cdac5a974e02ca2d8a100b10be42efae534d53c1037ddabd7e91dd021f322a3b8731a35ce0f2f305e3638866cb6b80cd60fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
